---
- name: Playbook per Nginx
  hosts: all
  become: true

  tasks:
    - name: Copia file con template
      template:
        src: templates/nginx.conf.j2
        dest: /usr/local/nginx-1.26.2/conf/nginx.conf
        owner: root
        group: root
        mode: '0600'
      notify: Riavvia Nginx

  handlers:
    - name: Riavvia Nginx
      service:
        name: nginx-custom #nginx-custom.service 
        state: restarted

