---
- name: Playbook per Nginx
  hosts: all
  become: true

  tasks:
    - name: Copia file di configurazione Nginx da macchina host a macchina remota
      template:
        src: templates/nginx.conf.j2
        dest: /usr/local/nginx-1.26.2/conf/nginx.conf
        owner: root
        group: root
        mode: '0600'
      notify: Riavvia Nginx

  handlers:
    - name: Se il file era già presente ed è stato modificato riavvia il service nginx-custom, altrimenti prosegue
      service:
        name: nginx-custom #nginx-custom.service 
        state: restarted

