---
- name: Playbook per Nginx
  hosts: all
  become: true

  tasks:
    - name: Aggiorna il file nginx.conf sulla macchina remota
      template:
        src: templates/nginx.conf.j2
        dest: /usr/local/nginx-1.26.2/conf/nginx.conf
        owner: root
        group: root
        mode: '0600'
      notify: Riavvia il servizio Nginx-custom

  handlers:
    - name: Riavvia il servizio Nginx-custom #solo se il file è stato modificato rispetto a quello già presente
      service:
        name: nginx-custom #nginx-custom.service 
        state: restarted

